[tool.poetry]
name = "frontend"
version = "0.2.0"
description = ""
authors = ["Remco S. van Maanen <r.s.vanmaanen@saxion.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.2.3"
requests = "^2.28.2"
matplotlib = "^3.7.1"
gunicorn = "^22.0.0"
olefile = "^0.46"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
